- hosts: Slaves
  name: TP2
  become: yes

  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - apache2
        - mysql-server
      register: aptinstall

    - ansible.builtin.package_facts:
        manager: auto 

    - name: Deploy index.html
      ansible.builtin.template:
        src: index.html.j2
        dest: /var/www/html/index.html
        force: yes
        owner: root
        group: root
        mode: "0644"
      when: '"apache2" in ansible_facts.packages'
      register: apache2index

    - name: restart apache
      ansible.builtin.service:
        name: apache2
        state: restarted
      when: apache2index is changed
