---
- hosts: all
  tasks:
    - name: Include all .yaml
      ansible.builtin.include_vars:
        dir: vars
        extensions:
          - 'yaml'

- name: Include a playbook from a collection
  ansible.builtin.import_playbook: bbc.ansible_course.tp8
