- hosts: Master
  name: Play with filters

  tasks:
    - name: Read CSV
      ansible.builtin.set_fact:
        temperature: "{{ lookup('file', 'temperature.csv') | community.general.from_csv | unique(attribute='time') | sort(attribute='time') }}"
      delegate_to: localhost

    - name: Get Paris Weather URI
      ansible.builtin.uri:
        url: https://api.open-meteo.com/v1/forecast?latitude=48.86&longitude=2.33&current=temperature_2m
        return_content: true
      register: weather_content
      delegate_to: localhost

    - name: Get Paris Weather
      ansible.builtin.set_fact:
        paris_weather: "{{ (weather_content.content | ansible.builtin.from_json).current }}"
      delegate_to: localhost

    - name: Which is warmer
      ansible.builtin.debug: # Soucis: il faut comparer l'heure et pas toute la date
        msg: "{{ (temperature | selectattr('time','equalto',paris_weather.time) ) }}" # .temperature < paris_weather.temperature_2m }}"
      delegate_to: localhost
