- hosts: web:db
  name: TP6 / prepare
  become: true
  tags: ["always","prepare"]

  tasks:
    - name: Refresh apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

- hosts: db
  name: TP6 / database
  become: true
  gather_facts: false
  tags: ["always", "database"]
  vars_files:
    - vars/db.yaml

  roles:
    - { role: geerlingguy.mysql , tag: ["always","database"] }

- name: Installer et configurer wordpress
  hosts: web
  become: true
  become_user: root

  tags: ["always", "wordpress"]
  vars_files:
    - vars/web.yaml

  roles:
    - { role: geerlingguy.php, tags: ["always","php"] }
    - { role: geerlingguy.apache, tags: ["always","apache"]}
    - { role: geerlingguy.apache-php-fpm, tags: ["always","apache","php","apache-php-fpm"] }

  tasks:
    - name: Create wordpress directory
      ansible.builtin.file:
        path: /var/www/wordpress/
        state: directory
        recurse: true

    - name: Download and unarchive wordpress
      ansible.builtin.unarchive:
        src: https://fr.wordpress.org/latest-fr_FR.zip
        dest: /var/www/
        remote_src: true
      tags:
        - always
        - archive

    - name: Configure wordpress wp-config.php
      ansible.builtin.template:
        src: wp-config.php.j2
        dest: /var/www/wordpress/wp-config.php
        mode: '0644'
      tags:
        - always
        - wp-config
